name: talon
description: A lightweight dependency free layer for making offline first apps.
version: 0.0.2
repository: https://github.com/jaaco/talon
documentation: https://docs.page/jaaco/talon

environment:
  sdk: ^3.3.3

dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
